### ISSUE TITLE
missin some info for make valid json for cura

### ISSUE THREAD

**Issue by exilaus** [adeebshihadeh/CuraProfileMaker#1]
Hi, thanks too much for your tool.
but  output not valid because you lose some tag.

for example i add my machine size and output are this :
"machine_settings": {
        "machine_width": 370,
        "machine_height": 300,
        "machine_depth": 370,

but is not valid for cura and no add new machine

Correct and valid output are:
 "machine_settings": {
        "machine_width":{"default":370},
        "machine_height":{"default":300},
        "machine_depth":{"default":370},

**Comment by adeebshihadeh** [comment]
Thanks for pointing that out
