### ISSUE TITLE
URL for current profiles is wrong

### ISSUE THREAD

**Issue by dmopalmer** [adeebshihadeh/CuraProfileMaker#10]
The 'Warning: Check here' at the top of the page points to the wrong URL and gets a 404.

Currently:
`https://github.com/Ultimaker/Cura/tree/master/resources/machines`
Should be:
`https://github.com/Ultimaker/Cura/tree/master/resources/definitions`

And I agree that /machines would be a better directory name than /definitions.

**Comment by adeebshihadeh** [comment]
thanks for letting me know. it's fixed
